$\textbf{Code Challenges}$

1. Develop a python function from scratch that will find the determinants of any $n \times n$ matrix.

2. Develop a python function from scratch that will find both the eigenvectors and eigenvalues of any $n \times n$ matrix.

3. Test your functions from a randomly generated $n \times n$ matrix.

In [24]:
import numpy as np

def find_determinant(matrix):
    if len(matrix)!=len(matrix[0]):
        print("bro square matrix allowed only")
        return 0

    n = len(matrix)
    det = 1

    for i in range(n):
        if matrix[i][i] == 0:
            for j in range(i + 1, n):
                if matrix[j][i] != 0:
                    matrix[i], matrix[j] = matrix[j], matrix[i]
                    det *= -1 
                    break

        if matrix[i][i] == 0:
            return 0 
        det *= matrix[i][i]

  
        for j in range(i + 1, n):
            factor = matrix[j][i] / matrix[i][i]
            for k in range(i + 1, n):
                matrix[j][k] -= factor * matrix[i][k]

    return det

def find_eigen(matrix):

    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues, eigenvectors

n = 3
n_matrix = np.random.randint(0, 10, size=(n, n))

print("Matrix:")
print(n_matrix)

determinant = find_determinant(n_matrix)
eigenvalues, eigenvectors = find_eigen(n_matrix)

print(f"\nDeterminant = {determinant}")
print(f"\nEigenvalue = {eigenvalues}")
print(f"\nEigenvector: \n{eigenvectors}")



Matrix:
[[9 9 7]
 [9 4 9]
 [4 9 0]]

Determinant = 45

Eigenvalue = [15.84508691 -4.03140442 -8.81368249]

Eigenvector: 
[[-0.85732869 -0.23907322  0.27559812]
 [-0.40111303 -0.3563613  -0.86752988]
 [-0.32263888  0.9032445   0.41405022]]
