# ASSIGNMENT 1
- The below python functions are developed to automate forward elimination.

In [2]:
import numpy as np

# Pythonic Solutions
# the following functions are the steps involved in forward elimination

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

- To complete the process of determining the solution, create a function or steps of function that will automate backward substitution.

In [17]:
def backward_substitution(U, b):
    n = U.shape[0] 
    x = np.zeros(n)  

    for i in range(n - 1, -1, -1):
        x[i] = b[i]
        for j in range(i + 1, n):
            x[i] -= U[i][j] * x[j]
        if U[i][i] != 0:
            x[i] /= U[i][i]
        else:
            x[i] = 0  # Set x[i] to 0 as an example

    return x


# Assignment 2

1. Provide reasons why each of the following equations is, or is not, a linear equation.
- $\cos{\theta}x+4y+z = \sqrt{3}$<br>
Because it satisfies the fundamental requirements of a linear equation, this equation can be classified as linear. After being raised to the first power, all three variables (x, y, and z) are merged with constant coefficients. The formulation of the equation does not include any nonlinearity, such as square roots or trigonometric functions.

- $cos{x}4y+z = \sqrt{3}$<br>
This equation is nonlinear, as opposed to linear. The fundamental requirement of linear equations is that variables must appear to the power of one (i.e., without exponents or functions applied to them). The existence of $cos x$ defies this requirement.

- $x^{-1}+7y+z = \sin{(\frac{\pi}{2})}$<br>
Because the variable x raised to the power of -1 violates the fundamental linearity criterion, this equation is nonlinear. The equation is not linear even though $sin(\frac{\pi}{2})$ is a linear constant.

- $x^1+y^1+z^1=0$<br>
Since all three variables (x, y, and z) have a power of 1, which is a property of linear equations, the equation is linear. There are no further nonlinear operations, such as square roots or trigonometric functions, involved; these variables are just combined with coefficients of 1. In line with the characteristics of a linear equation, the right-hand side is also a constant value.

---

2. Find the solutions to the linear equations:
- $2x_1+3x_2 =5$

Manual Solution:<br>
$
2x_1+3x_2 =5 \\
\frac{2x_1}{2} = \frac{5 - 3x_2}{2} \\
\boxed{x_1 = \frac{5}{2} - \frac{3}{2}x_2}
$

Pythonic Solution:

In [7]:
import sympy as sp

x1, x2 = sp.symbols('x1 x2')
equation = sp.Eq(2*x1 + 3*x2, 5)
solution = sp.solve(equation, (x1, x2))

print("Result: ")
print(solution)

Result: 
[(5/2 - 3*x2/2, x2)]


- $4x_1+3x_2+2x_3=1$

Manual Solution:<br>
$
4x_1+3x_2+2x_3 = 1 \\
\frac{4x_1}{4} = \frac{1 - 3x_2 - 2x_3}{4} \\
\boxed{x_1 = \frac{1}{4} - \frac{3}{4}x_2 - \frac{1}{2}x_3}
$

Pythonic Solution:

In [8]:
import sympy as sp
x1, x2, x3 = sp.symbols('x1 x2 x3')
equation = sp.Eq(4*x1 + 3*x2 + 2*x3, 1)
solution = sp.solve(equation, (x1, x2, x3))

print("Result: ")
print(solution)

Result: 
[(-3*x2/4 - x3/2 + 1/4, x2, x3)]


- $3x-6y=0$

Manual Solution:<br>
$
3x - 6y = 0 \\
\frac{3x}{3} = \frac{6y}{3} \\
\boxed{x = 2y}
$

Pythonic Solution:

In [10]:
import sympy as sp
x, y = sp.symbols('x y')
equation = sp.Eq(3*x - 6*y, 0)
solution = sp.solve(equation, (x, y))

print("Result: ")
print(solution)

Result: 
[(2*y, y)]


---
3. Solve the following systems of linear equations<br>
a. 
$
x-y=0 \\
2x+y = 3
$

Manual Solution:<br>

$Forward Elimination:$<br>
$ \\
-2(x - y = 0) \\
-2x + 2y = 0 \space + \space2x + y = 3
\\ = \frac{3y}{3} = \frac{3}{3} \\
\boxed{y = 1} \\
$


$Backward Substitution:$<br> 
$\\
x - (1) = 0 \\
\boxed{x = 1}
$

Pythonic Solution:

In [12]:
A = np.array([[1, -1],
              [2, 1]])

# coefficients
b = np.array([0, 3])

# Perform forward elimination to transform A into upper triangular form U
# Step 1: Row 2 = Row 2 - 2 * Row 1
A = RowAdd(A, 0, 1, -2)

# Now, A is in upper triangular form, and we can use BackwardSubstitution to find the solution
solution = backward_substitution(A, b)

# Print the solution
print("Solution vector x & y:")
print(solution)

Solution vector x & y:
[1.0, 1.0]


b.
$
x+5y= -1 \\
-x+y = -5 \\
2x+4y = 4
$

Manual Solution: <br><br>
$
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    -1 & 1 &\bigm| & -5 \\
    2 & 4 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 6 &\bigm| & -6 \\
    2 & 4 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 6 &\bigm| & -6 \\
    0 & -6 &\bigm| & 6 \\
\end{pmatrix}
\xrightarrow{\frac{1}{6}\text{R}_{2}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
    0 & -6 &\bigm| & 6 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - 5\text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & 4 \\
    0 & 1 &\bigm| & -1 \\
    0 & -6 &\bigm| & 6 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + 6\text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & 4 \\
    0 & 1 &\bigm| & -1 \\
    0 & 0 &\bigm| & 0 \\
\end{pmatrix}
$
<br><br>
Backward Substitution:<br>
$x = 4 + 0t$<br>
$y = -1 + 0t$ <br>
i.e. x = 4 & y = -1

Pythonic Solution:

In [16]:
A = np.array([[1, 5, -1],
              [-1, 1, -5],
              [2, 4, 4]])

print("A (Original)")
print(A,'\n')
A = RowAdd(A, 0, 1, 1)
print("A1")
print(A,'\n')
A = RowAdd(A, 0, 2, -2)
print("A2")
print(A,'\n')
A = RowScale(A, 1, 1/6)
print("A3")
print(A,'\n')
A = RowAdd(A, 1, 0, -5)
print("A4")
print(A,'\n')
A = RowAdd(A, 1, 2, 6)
print("A5")
print(A,'\n')

last_entries = [] #to get the coefficient array for b

for row in A:
    last_entry = row[-1]
    last_entries.append(last_entry)

b = np.array(last_entries)

solution = backward_substitution(A, b)

print("Solution to vector x, y & z:")
print(solution)

A (Original)
[[ 1  5 -1]
 [-1  1 -5]
 [ 2  4  4]] 

A1
[[ 1.  5. -1.]
 [ 0.  6. -6.]
 [ 2.  4.  4.]] 

A2
[[ 1.  5. -1.]
 [ 0.  6. -6.]
 [ 0. -6.  6.]] 

A3
[[ 1.  5. -1.]
 [ 0.  1. -1.]
 [ 0. -6.  6.]] 

A4
[[ 1.  0.  4.]
 [ 0.  1. -1.]
 [ 0. -6.  6.]] 

A5
[[ 1.  0.  4.]
 [ 0.  1. -1.]
 [ 0.  0.  0.]] 

Solution to vector x, y & z:
[ 4. -1.  0.]


c.
$
2x_1+3x_2-x_3= -1 \\
x_1+x_3 = 0 \\
-x_1+2x_2-2x_3 = 0
$

Manual Solution: <br><br>
$
\begin{pmatrix}
    2 & 3 & -1 &\bigm| & -1 \\
    1 & 0 & 1 &\bigm| & 0 \\
    -1 & 2 & -2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{1}{2}\text{R}_{1}}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    1 & 0 & 1 &\bigm| & 0 \\
    -1 & 2 & -2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    0 & \frac{-3}{2} & \frac{3}{2} &\bigm| & \frac{1}{2} \\
    -1 & 2 & -2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{1}}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    0 & \frac{-3}{2} & \frac{3}{2} &\bigm| & \frac{1}{2} \\
    0 & \frac{7}{2} & \frac{-5}{2} &\bigm| & \frac{-1}{2} \\
\end{pmatrix}
\xrightarrow{\frac{-2}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    0 & 1 & -1 &\bigm| & \frac{-1}{3} \\
    0 & \frac{7}{2} & \frac{-5}{2} &\bigm| & \frac{-1}{2} \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \frac{7}{2}\text{R}_{2}}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    0 & 1 & -1 &\bigm| & \frac{-1}{3} \\
    0 & 0 & 1 &\bigm| & \frac{-5}{9} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \frac{3}{2}\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & \frac{1}{3} &\bigm| & \frac{1}{3} \\
    0 & 1 & -1 &\bigm| & \frac{-1}{3} \\
    0 & 0 & 1 &\bigm| & \frac{-5}{9} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \frac{1}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & -1 &\bigm| & \frac{-1}{3} \\
    0 & 0 & 1 &\bigm| & \frac{-5}{9} \\
\end{pmatrix}
$

<br><br>
Backward Substitution:<br>
$\boxed{x_1 = 0}$<br>
$\boxed{x_3 = -\frac{5}{9}}$ <br>
$x_2 - x_3 = -\frac{1}{3}$<br>
$x_2 - (-\frac{5}{9}) = -\frac{1}{3}$<br>
$x_2 = -\frac{1}{3} - \frac{5}{9}$<br>
$\boxed{x_2 = -\frac{8}{9}}$

Pythonic Solution:

In [20]:
# pythonic solution #
A = np.array([[2, 3, -1, -1],
              [1, 0, 1, 0],
              [-1, 2, -2, 0]])

print("A (Original)")
print(A,'\n')
A = RowScale(A, 0, 1/2)
print("A1")
print(A,'\n')
A = RowAdd(A, 0, 1, -1)
print("A2")
print(A,'\n')
A = RowAdd(A, 0, 2, 1)
print("A3")
print(A,'\n')
A = RowScale(A, 1, -2/3)
print("A4")
print(A,'\n')
A = RowAdd(A, 1, 2, -7/2)
print("A5")
print(A,'\n')

A = RowAdd(A, 1, 0, -3/2) #smth is wrong here jusko
print("A6")
print(A,'\n')

A = RowAdd(A, 1, 0, 1/2)
print("A7")
print(A,'\n')


last_entries = [] #to get the coefficient array for b

for row in A:
    last_entry = row[-1]
    last_entries.append(last_entry)

b = np.array(last_entries)

solution = backward_substitution(A, b)

print("Solution to vector x_1, x_2 & x_3:")
print(solution)

A (Original)
[[ 2  3 -1 -1]
 [ 1  0  1  0]
 [-1  2 -2  0]] 

A1
[[ 1.   1.5 -0.5 -0.5]
 [ 1.   0.   1.   0. ]
 [-1.   2.  -2.   0. ]] 

A2
[[ 1.   1.5 -0.5 -0.5]
 [ 0.  -1.5  1.5  0.5]
 [-1.   2.  -2.   0. ]] 

A3
[[ 1.   1.5 -0.5 -0.5]
 [ 0.  -1.5  1.5  0.5]
 [ 0.   3.5 -2.5 -0.5]] 

A4
[[ 1.          1.5        -0.5        -0.5       ]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          3.5        -2.5        -0.5       ]] 

A5
[[ 1.          1.5        -0.5        -0.5       ]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          0.          1.          0.66666667]] 

A6
[[ 1.          0.          1.          0.        ]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          0.          1.          0.66666667]] 

A7
[[ 1.          0.5         0.5        -0.16666667]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          0.          1.          0.66666667]] 

Solution to vector x_1, x_2 & x_3:
[-0.66666667  0.33333333  0.66666667]


---
4. Provide reasons why the given matrices are either a row echelon, a reduced row echelon, or niether both.<br>
a. <br>
\begin{pmatrix}
   1 & 0 & 1 \\
   0 & 0 & 3 \\
   0 & 1 & 0 \\
\end{pmatrix}<br>
-Since the leading entry in Row 2 is greater than the bottom-right entry in Row 1, this matrix is not in row echelon form. Furthermore, since it must first be in row echelon form, it does not satisfy the requirements for reduced row echelon form (RREF). Furthermore, there are other non-zero entries in each of the columns other than the leading entries.

<br>
b. <br>
\begin{pmatrix}
   7 & 0 & 1 & 0 \\
   0 & 1 & -1 & 4 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}<br>
-Because the leading entries in Rows 1 and 2 are positioned correctly and there are zeros below the leading entry in Row 1, it satisfies the requirements for row echelon form (REF). But since the leading entry in Row 1 is not 1, it is not reduced row echelon form (RREF).

<br>
c. <br>
\begin{pmatrix}
   0 & 1 & 3 & 0 \\
   0 & 0 & 0 & 1 \\
\end{pmatrix}<br>
-Due to the fact that every row has a leading entry of 1 and the bottom row has the greatest number of zeros, this matrix is in reduced row echelon form, or RREF.

<br>
d. <br>
\begin{pmatrix}
   0 & 0 & 0 \\
   0 & 0 & 0 \\
   0 & 0 & 0 \\
\end{pmatrix}<br>
-Since all of the entries are zeroes, it is a Zero/Null Matrix and does not meet the requirements for either row echelon form (REF) or reduced row echelon form (RREF).

<br>
e. <br>
\begin{pmatrix}
   1 & 0 & 3 & -4 & 0 \\
   0 & 0 & 0 & 0 & 0 \\
   0 & 1 & 5 & 0 & 1 \\
\end{pmatrix}<br>
-Not in row echelon form (REF), since Row 2 contains the row with the greatest number of zeros, not the bottom row. Since it must first meet the requirements for row echelon form, it is not eligible to be reduced row echelon form (RREF).

<br>
f. <br>
\begin{pmatrix}
   0 & 0 & 1 \\
   0 & 1 & 0 \\
   1 & 0 & 0 \\
\end{pmatrix}<br>
-This matrix has leading entries of 1 that are encircled by zeros, indicating that it is in reduced row echelon form (RREF).

<br>
g. <br>
\begin{pmatrix}
   1 & 2 & 3 \\
   1 & 0 & 0 \\
   0 & 1 & 1 \\
   0 & 0 & 1 \\
\end{pmatrix}<br>
-Since non-zero entries are found beneath each leading entry, it satisfies the requirements for row echelon form (REF). The entries in Rows 3 through 4 are also positioned correctly.

<br>
h. <br>
\begin{pmatrix}
   2 & 1 & 3 & 5 \\
   0 & 0 & 1 & -1 \\
   0 & 0 & 0 & 3 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}
<br>
-Since the row with the most zeros is at the bottom, this matrix complies with the row echelon form rule (REF). Additionally, there are zeros beneath every leading entry.

---
5. Solve the following systems of linear equations<br>
a.<br> 
\begin{equation}
x_1+2x_2-3x_3=9 \\
2x_1-x_2-x_3=0 \\
4x_1-x_2+x_3=4 \\
\end{equation}
<br>

Manual Solution:<br><br>
$
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    2 & -1 & -1 &\bigm| & 0 \\
    4 & -1 & 1 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & -5 & 5 &\bigm| & -18 \\
    4 & -1 & 1 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 4\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & -5 & 5 &\bigm| & -18 \\
    0 & -9 & 13 &\bigm| & -32 \\
\end{pmatrix}
\xrightarrow{-\frac{1}{5}\text{R}_{2}}
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & 1 & -1 &\bigm| & \frac{18}{5} \\
    0 & -9 & 13 &\bigm| & -32 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 9\text{R}_{2}}
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & 1 & -1 &\bigm| & \frac{18}{5} \\
    0 & 0 & 4 &\bigm| & -\frac{2}{5} \\
\end{pmatrix} \\
\\
New Equations:\\
= x_1 + 2x_2 - 3x_3 = 9\\
= x_2 - (-x_3) = \frac{18}{5}\\
= 4x_3 = -\frac{2}{5}\\
\\
Backwards Substitution: \\
\frac{4x_3}{4} = \frac{\frac{2}{5}}{4}\\
\boxed{x_3 = \frac{1}{10}}\\
\\
x_2 - (-x_3) = \frac{18}{5}\\
x_2 - (\frac{1}{10}) = \frac{18}{5}\\
x_2 = \frac{18}{5} + \frac{1}{10}\\
\boxed{x_2 = \frac{37}{10}}\\
x_1 + 2x_2 - 3x_3 = 9\\
x_1 + 2(\frac{37}{10}) - 3(\frac{1}{10}) = 9\\
x_1 + \frac{37}{5}) - \frac{3}{10} = 9\\
\boxed{x_1 = \frac{19}{10}}\\
$

Pythonic Solution:

In [22]:
A = np.array([[1, 2, -3, 9],
              [2, -1, -1, 0],
              [4, -1, 1, 4]])

print("A (Original)")
print(A,'\n')
A = RowAdd(A, 0, 1, -2)
print("A1")
print(A,'\n')
A = RowAdd(A, 0, 2, -4)
print("A2")
print(A,'\n')
A = RowScale(A, 1, -1/5)
print("A3")
print(A,'\n')
A = RowAdd(A, 1, 2, 9)
print("A4")
print(A,'\n')


last_entries = [] #to get the coefficient array for b

for row in A:
    last_entry = row[-1]
    last_entries.append(last_entry)

b = np.array(last_entries)

solution = backward_substitution(A, b)

print("Solution to vectors x1, x2 & x3:")
print(solution)

A (Original)
[[ 1  2 -3  9]
 [ 2 -1 -1  0]
 [ 4 -1  1  4]] 

A1
[[  1.   2.  -3.   9.]
 [  0.  -5.   5. -18.]
 [  4.  -1.   1.   4.]] 

A2
[[  1.   2.  -3.   9.]
 [  0.  -5.   5. -18.]
 [  0.  -9.  13. -32.]] 

A3
[[  1.    2.   -3.    9. ]
 [ -0.    1.   -1.    3.6]
 [  0.   -9.   13.  -32. ]] 

A4
[[ 1.   2.  -3.   9. ]
 [-0.   1.  -1.   3.6]
 [ 0.   0.   4.   0.4]] 

Solution to vectors x1, x2 & x3:
[1.9 3.7 0.1]


<br>
b. <br>
\begin{equation}
x+2y= -1 \\
2x+y+z = 1 \\
-x+y-z = -1
\end{equation}

Manual Solution:<br><br>
$
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    2 & 1 & 1 &\bigm| & 1 \\
    -1 & 1 & -1 &\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & -3 & 1 &\bigm| & 3 \\
    -1 & 1 & -1 &\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{1}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & -3 & 1 &\bigm| & 3 \\
    0 & 3 & -1 &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{2}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & -3 & 1 &\bigm| & 3 \\
    0 & 0 & 0 &\bigm| & 1 \\
\end{pmatrix}
$
<br><br>
- L3: 0z = there is no solution to this due to 1 being not possible.

Pythonic Solution:

In [26]:
A = np.array([[1, 2, 0, -1],
              [2, 1, 1, 1],
              [-1, 1, -1, -1]])

print("A (Original)")
print(A,'\n')
A = RowAdd(A, 0, 1, -2)
print("A1")
print(A,'\n')
A = RowAdd(A, 0, 2, 1)
print("A2")
print(A,'\n')
A = RowAdd(A, 1, 2, 1)
print("A3")
print(A,'\n')


last_entries = [] #to get the coefficient array for b

for row in A:
    last_entry = row[-1]
    last_entries.append(last_entry)

b = np.array(last_entries)

solution = backward_substitution(A, b)

print("Solution to vectors x, y & z:")
print(solution)
print("Not possible since 0x + 0y + 0z != 1")

A (Original)
[[ 1  2  0 -1]
 [ 2  1  1  1]
 [-1  1 -1 -1]] 

A1
[[ 1.  2.  0. -1.]
 [ 0. -3.  1.  3.]
 [-1.  1. -1. -1.]] 

A2
[[ 1.  2.  0. -1.]
 [ 0. -3.  1.  3.]
 [ 0.  3. -1. -2.]] 

A3
[[ 1.  2.  0. -1.]
 [ 0. -3.  1.  3.]
 [ 0.  0.  0.  1.]] 

Solution to vectors x, y & z:
[ 1. -1.  0.]
Not possible since 0x + 0y + 0z != 1


c. <br>
\begin{equation}
x_1-3x_2-2x_3=0 \\
-x_1+2x_2+x_3=0 \\
2x_1+4x_2+6x_3=0 \\
\end{equation}
<br>

Manual Solution:<br><br>
$
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    -1 & 2 & 1 &\bigm| & 0 \\
    2 & 4 & 6 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & -1 & -1 &\bigm| & 0 \\
    2 & 4 & 6 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & -1 & -1 &\bigm| & 0 \\
    0 & 10 & 10 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + 10\text{R}_{2}}
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & -1 & -1 &\bigm| & 0 \\
    0 & 0 & 0 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - 3\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 1 &\bigm| & 0 \\
    0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 &\bigm| & 0 \\
\end{pmatrix}
$
<br><br>
- L3: 0x1 + 0x2 + 0x3 = 0, x3 can have any value.<br>
L2: x2 + x3 = 0 = x2 = -x3<br>
L1: x1 + x3 = 0 = x1 + -x3<br>

Pythonic Solution:

In [28]:
A = np.array([[1, -3, -2, 0],
              [-1, 2, 1, 0],
              [2, 4, 6, 0]])

print("A (Original)")
print(A,'\n')
A = RowAdd(A, 0, 1, 1)
print("A1")
print(A,'\n')
A = RowAdd(A, 0, 2, -2)
print("A2")
print(A,'\n')
A = RowAdd(A, 1, 2, 10)
print("A3")
print(A,'\n')
A = RowAdd(A, 1, 0, -3)
print("A4")
print(A,'\n')


last_entries = [] #to get the coefficient array for b

for row in A:
    last_entry = row[-1]
    last_entries.append(last_entry)

b = np.array(last_entries)

solution = backward_substitution(A, b)

print("Solution to vectors x1, x2 & x3:")
print(solution)

A (Original)
[[ 1 -3 -2  0]
 [-1  2  1  0]
 [ 2  4  6  0]] 

A1
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 2.  4.  6.  0.]] 

A2
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 0. 10. 10.  0.]] 

A3
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 0.  0.  0.  0.]] 

A4
[[ 1.  0.  1.  0.]
 [ 0. -1. -1.  0.]
 [ 0.  0.  0.  0.]] 

Solution to vectors x1, x2 & x3:
[ 0. -0.  0.]


d. <br>
\begin{equation}
w+x+2y+z=1 \\
w-x-y+z=0 \\
x+y=1 \\
w+x+z=2
\end{equation}
<br>

Manual Solution:<br><br>
$
\begin{align*}
w + x + 2y + z &= 1 \\
w - x - y + z &= 0 \\
x + y &= 1 \\
w + x + z &= 2
\end{align*}\\
$
<br><br>
$
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
1 & -1 & -1 & 1 & \big| & 0 \\
0 & 1 & 1 & 0 & \big| & 1 \\
1 & 1 & 0 & 1 & \big| & 2 \\
\end{bmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
0 & -2 & -3 & 0 & \big| & -1 \\
0 & 1 & 1 & 0 & \big| & 1 \\
1 & 1 & 0 & 1 & \big| & 2 \\
\end{bmatrix}
\xrightarrow{\text{R}_{3} + 2\text{R}_{2}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
0 & -2 & -3 & 0 & \big| & -1 \\
0 & 0 & 1 & 0 & \big| & 1 \\
1 & 1 & 0 & 1 & \big| & 2 \\
\end{bmatrix}
\xrightarrow{\text{R}_{4} + \text{R}_{3}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
0 & -2 & -3 & 0 & \big| & -1 \\
0 & 0 & 1 & 0 & \big| & 1 \\
1 & 1 & -1 & 1 & \big| & 3 \\
\end{bmatrix}
\xrightarrow{-1\text{R}_{3}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
0 & -2 & -3 & 0 & \big| & -1 \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & -1 & 1 & \big| & 3 \\
\end{bmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{3}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
0 & -2 & 1 & 0 & \big| & 1 \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & -1 & 1 & \big| & 3 \\
\end{bmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{3}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 2 \\
0 & -2 & 1 & 0 & \big| & 1 \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & -1 & 1 & \big| & 3 \\
\end{bmatrix}
\xrightarrow{\text{R}_{4} - \text{R}_{3}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 2 \\
0 & -2 & 1 & 0 & \big| & 1 \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & 0 & 1 & \big| & 4 \\
\end{bmatrix}
\xrightarrow{\text{R}_{1} - 2\text{R}_{3}}
\begin{bmatrix}
1 & 1 & 0 & 1 & \big| & 4 \\
0 & -2 & 1 & 0 & \big| & 1 \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & 0 & 1 & \big| & 4 \\
\end{bmatrix}
\xrightarrow{-\frac{1}{2}\text{R}_{2}}
\begin{bmatrix}
1 & 1 & 0 & 1 & \big| & 4 \\
0 & 1 & -\frac{1}{2} & 0 & \big| & -\frac{1}{2} \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & 0 & 1 & \big| & 4 \\
\end{bmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{2}}
\begin{bmatrix}
1 & 0 & \frac{1}{2} & 1 & \big| & \frac{9}{2} \\
0 & 1 & -\frac{1}{2} & 0 & \big| & -\frac{1}{2} \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & 0 & 1 & \big| & 4 \\
\end{bmatrix}
\xrightarrow{\text{R}_{4} - \text{R}_{1}}
\begin{bmatrix}
1 & 0 & \frac{1}{2} & 1 & \big| & \frac{9}{2} \\
0 & 1 & -\frac{1}{2} & 0 & \big| & -\frac{1}{2} \\
0 & 0 & -1 & 0 & \big| & -1 \\
0 & 0 & 1 & 1 & \big| & 4 \\
\end{bmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{4}}
\begin{bmatrix}
1 & 0 & 0 & 0 & \big| & 0 \\
0 & 1 & 0 & 0 & \big| & -\frac{1}{2} \\
0 & 0 & -1 & 0 & \big| & -1 \\
0 & 0 & 1 & 1 & \big| & 4 \\
\end{bmatrix}
$

\begin{align*}
w &= 0 \\
x &= -\frac{1}{2} \\
y &= -1 \\
z &= 0 \\
\end{align*}
<br>

Pythonic Solution:

In [30]:
# pythonic solution #
A = np.array([[1, 1, 2, 1, 1],
              [1, -1, -1, 1, 0],
              [0, 1, 1, 0, 1],
              [1, 1, 0, 1, 2]])

print("A (Original)")
print(A,'\n')
A = RowAdd(A, 0, 1, -1)
print("A1")
print(A,'\n')
A = RowAdd(A, 1, 2, 2)
print("A2")
print(A,'\n')
A = RowAdd(A, 2, 3, 1)
print("A3")
print(A,'\n')
A = RowScale(A, 2, -1)
print("A4")
print(A,'\n')
A = RowAdd(A, 2, 1, -2)
print("A5")
print(A,'\n')
A = RowAdd(A, 2, 0, -1)
print("A6")
print(A,'\n')
A = RowAdd(A, 2, 3, -1)
print("A7")
print(A,'\n')
A = RowAdd(A, 2, 0, -2)
print("A8")
print(A,'\n')
A = RowScale(A, 1, -1/2)
print("A9")
print(A,'\n')
A = RowAdd(A, 1, 0, -1)
print("A10")
print(A,'\n')
A = RowAdd(A, 0, 3, -1)
print("A11")
print(A,'\n')
A = RowAdd(A, 3, 0, -1)
print("A12")
print(A,'\n')


last_entries = [] #to get the coefficient array for b

for row in A:
    last_entry = row[-1]
    last_entries.append(last_entry)

b = np.array(last_entries)

solution = backward_substitution(A, b)

print("Solution to vectors x, y, z, w:")
print(solution)

A (Original)
[[ 1  1  2  1  1]
 [ 1 -1 -1  1  0]
 [ 0  1  1  0  1]
 [ 1  1  0  1  2]] 

A1
[[ 1.  1.  2.  1.  1.]
 [ 0. -2. -3.  0. -1.]
 [ 0.  1.  1.  0.  1.]
 [ 1.  1.  0.  1.  2.]] 

A2
[[ 1.  1.  2.  1.  1.]
 [ 0. -2. -3.  0. -1.]
 [ 0. -3. -5.  0. -1.]
 [ 1.  1.  0.  1.  2.]] 

A3
[[ 1.  1.  2.  1.  1.]
 [ 0. -2. -3.  0. -1.]
 [ 0. -3. -5.  0. -1.]
 [ 1. -2. -5.  1.  1.]] 

A4
[[ 1.  1.  2.  1.  1.]
 [ 0. -2. -3.  0. -1.]
 [-0.  3.  5. -0.  1.]
 [ 1. -2. -5.  1.  1.]] 

A5
[[  1.   1.   2.   1.   1.]
 [  0.  -8. -13.   0.  -3.]
 [ -0.   3.   5.  -0.   1.]
 [  1.  -2.  -5.   1.   1.]] 

A6
[[  1.  -2.  -3.   1.   0.]
 [  0.  -8. -13.   0.  -3.]
 [ -0.   3.   5.  -0.   1.]
 [  1.  -2.  -5.   1.   1.]] 

A7
[[  1.  -2.  -3.   1.   0.]
 [  0.  -8. -13.   0.  -3.]
 [ -0.   3.   5.  -0.   1.]
 [  1.  -5. -10.   1.   0.]] 

A8
[[  1.  -8. -13.   1.  -2.]
 [  0.  -8. -13.   0.  -3.]
 [ -0.   3.   5.  -0.   1.]
 [  1.  -5. -10.   1.   0.]] 

A9
[[  1.   -8.  -13.    1.   -2. ]
 [ -0.    4.

---
6. Determine if the vectors are linear combinations<br>
a. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} -1 \\ 3 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 2 \\ -6 \end{bmatrix}\\
\end{equation}
<br>
Manual Solution:<br>
\[
x \textbf{u}_2 + y \textbf{u}_3 = \textbf{v}
\]
\begin{align*}
-x + 2y &= 1 \\
3x - 6y &= 2
\end{align*}
<br>
$
\begin{bmatrix}
-1 & 2 & | & 1 \\
3 & -6 & | & 2
\end{bmatrix}
\xrightarrow{\text{R}_{2} + 3\text{R}_{1}}
\begin{bmatrix}
-1 & 2 & | & 1 \\
0 & 0 & | & 5
\end{bmatrix}
$

- This system is inconsistent because of the last row, which implies that 0 cannot equal 5. Consequently, vector v cannot be represented by combining u2 and u3 linearly.

<br><br>

b. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}
<br>
Manual Solution:
\begin{align*}
x + 0 &= 1 \\
x + y &= 2 \\
0 + y &= 3
\end{align*}

$
\begin{bmatrix}
1 & 0 & | & 1 \\
1 & 1 & | & 2 \\
0 & 1 & | & 3
\end{bmatrix}
\xrightarrow{\text{R}_{2} - \tb. <br>
\begin{equation}
x+2y= -1 \\
2x+y+z = 1 \\
-x+y-z = -1
\end{equation}ext{R}_{1}}
\begin{bmatrix}
1 & 0 & | & 1 \\
0 & 1 & | & 1 \\
0 & 1 & | & 3
\end{bmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
\begin{bmatrix}
1 & 0 & | & 1 \\
0 & 1 & | & 1 \\
0 & 0 & | & 2
\end{bmatrix}
$
<br>
- Both x and y equal 1. The vector is thus a linear combination of the supplied vectors.
<br><br>
c. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 3 \\ 1 \\ -2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}
<br>
Manual Solution:

\begin{align*}
x + 0 &= 3 \\
x + y &= 1 \\
0 + y &= -2
\end{align*}
<br>
$
\begin{bmatrix}
1 & 0 & | & 3 \\
1 & 1 & | & 1 \\
0 & 1 & | & -2
\end{bmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{bmatrix}
1 & 0 & | & 3 \\
0 & 1 & | & -2 \\
0 & 1 & | & -2
\end{bmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
\begin{bmatrix}
1 & 0 & | & 3 \\
0 & 1 & | & -2 \\
0 & 0 & | & 0
\end{bmatrix}
$
<br>
- The system has an infinite number of solutions and is now consistent. There are thus several solutions for x and y, and vector v is a linear combination of u2 and u3.
<br><br>

---
7. Show that the following vectors are a span: <br>
a.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 1 \\ \end{bmatrix}
\begin{bmatrix}1 \\ -1 \\ \end{bmatrix}
\end{pmatrix}
$
<br><br>
Manual Solution:<br>
$
\begin{bmatrix}
1 & 1 & | & x \\
1 & -1 & | & y
\end{bmatrix}
\xrightarrow{}
\begin{bmatrix}
\begin{array}{cccc|c}
1 & 1 & | & x & (R_1) \\
1 & -1 & | & y & (R_2)
\end{array}
\end{bmatrix}
\xrightarrow{\text{R}_{2} -\text{R}_{1}}
\begin{bmatrix}
\begin{array}{cccc|c}
1 & 1 & | & x & (R_1) \\
0 & -2 & | & y - x & (R_2 - R_1)
\end{array}
\end{bmatrix}
\xrightarrow{\frac{1}{-2}\text{R}_{2}}
\begin{bmatrix}
\begin{array}{cccc|c}
1 & 1 & | & x & (R_1) \\
0 & 1 & | & \frac{y - x}{-2} & \left(\frac{1}{-2}\right)R_2
\end{array}
\end{bmatrix}
$ <br>
- The following vectors are a span.
<br><br>
b.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
\begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
\begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
\end{pmatrix}
$
<br><br>
Manual Solution: <br>
\begin{align*}
a + b &= x \\
b + c &= y \\
a + c &= z
\end{align*}
$
\begin{bmatrix}
1 & 1 & 0 & | & x \\
0 & 1 & 1 & | & y \\
1 & 0 & 1 & | & z
\end{bmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{1}}
\begin{bmatrix}
1 & 1 & 0 & | & x \\
0 & 1 & 1 & | & y \\
0 & -1 & 1 & | & z - x
\end{bmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{2}}
\begin{bmatrix}
1 & 1 & 0 & | & x \\
0 & 1 & 1 & | & y \\
0 & 0 & 2 & | & y - x + z
\end{bmatrix}
$
<br>
- The vectore are a span as long as \(2\) divides \(y - x + z\).
<br><br>
c.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
\begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
\begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
\end{pmatrix}
$
<br><br>

Manual Solution: <br>
\begin{align*}
a + b &= x \\
b + c &= y \\
a + c &= z
\end{align*}
$
\begin{bmatrix}
1 & 1 & 0 & | & x \\
0 & 1 & 1 & | & y \\
1 & 0 & 1 & | & z
\end{bmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{1}}
\begin{bmatrix}
1 & 1 & 0 & | & x \\
0 & 1 & 1 & | & y \\
0 & -1 & 1 & | & z - x
\end{bmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{2}}
\begin{bmatrix}
1 & 1 & 0 & | & x \\
0 & 1 & 1 & | & y \\
0 & 0 & 2 & | & y - x + z
\end{bmatrix}
$
<br>
- The vectore are a span as long as \(2\) divides \(y - x + z\).
<br><br>

8. Show that the following vectors are linearly independent:<br>
a. <br>
\begin{equation}
\begin{bmatrix} 3 \\ -1 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} -1 \\ 2 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 1 \\ 1 \\ 3 \\ 1 \end{bmatrix}
\begin{bmatrix} -1 \\ -1 \\ 1 \\ 3 \end{bmatrix}
\end{equation}<br>
- m = 4 & n = 4; 4 $\ngeq$ 4. The following vectors are linearly independent according to conditions 3 and 4. <br>
b. <br>
\begin{equation}
\begin{bmatrix} 0 \\ 0 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 0 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 4 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\end{equation}<br>
- m = 4 & n = 4.<br>
L1: 4z = 0; z = 0.<br>
L2: 3w + 3z; w = 0.<br>
L3: 2y + 2w + 2z = 0; y = 0.<br>
L4: x + 0 + 0 + 0 = 0; x = 0.<br>
As a result, by condition 1, the vectors are linearly independent.<br>

c. <br>
\begin{equation}
\begin{bmatrix} 1 \\ -1 \\ 1 \\ 0 \end{bmatrix}
\begin{bmatrix} -1 \\ 1 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 1 \\ 0 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 0 \\ 1 \\ -1 \\ 1 \end{bmatrix}
\end{equation}<br>
- m = 4 & n = 4. Accordingly, by condition 4, they are linearly independent.<br>